version: '3'
services:
    generated-api:
        container_name: generated-api
        build:
            context: ./
            dockerfile: Dockerfile
        image: generated_api:latest
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/patientdb    
            - SPRING_DATASOURCE_USERNAME=dbuser
            - SPRING_DATASOURCE_PASSWORD=dbuser
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network

    db:
        image: 'postgres:13.1-alpine'
        container_name: db
        environment:
            - POSTGRES_USER= postgres                               
            - POSTGRES_PASSWORD=password                          
        volumes:
          - "./database/mtdb:/var/lib/postgresql/data"
        ports:
            - 5432:5432
networks:
    spring-cloud-network:
        driver: bridge
